name: SourceMod Plugin Workflow

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download sourcemod
      run: |
        wget "http://www.sourcemod.net/latest.php?version=1.11&os=linux" -O sourcemod.tar.gz
        tar -xzf sourcemod.tar.gz
    - name: Give spcomp the required permissions
      run: chmod +x addons/sourcemod/scripting/spcomp
    - name: Compiling the plugin
      run: addons/sourcemod/scripting/spcomp -E addons/sourcemod/scripting/shavit-report.sp
